### ISSUE TITLE
Add support for Clarabel.rs

### ISSUE THREAD

**Issue by goulart-paul** [rust-or/good_lp#27]
Polite request to add support for our native Rust solver here:
https://github.com/oxfordcontrol/Clarabel.rs

I'm happy to help with doing so.  Is there some documentation that you could point to for implementing new solver backends?

**Comment by lovasoa** [comment]
Hello and sorry for the very late reply ! I'd be happy to help you add support for carabel in good_lp !

What you need to do:
 - add carabel as an optional dependency in https://github.com/rust-or/good_lp/blob/main/Cargo.toml#L20
 - add a file named `carabel.rs` in the solvers folder https://github.com/rust-or/good_lp/tree/main/src/solvers
    - you can copy minilp,  our smallest solver interface, as a starting point.
    - implement a function named carabel that takes an `UnsolvedProblem` and returns a `CarabelProblem`, which will be a wrapper around the problem type exposed by carabel. carabel seems to be quite low-level, so I suggest you just store the matrices in a format that makes them inexpensive to update when `add_constraint` is called
    - implement the `SolverModel` trait for your new `CarabelProblem` type

Don't hesitate to open a draft PR as soon as you start and to ask for help there, I'll be glad to help !

**Comment by lovasoa** [comment]
I created a [`CONTRIBUTING.md`](https://github.com/rust-or/good_lp/blob/main/CONTRIBUTING.md) for this repo, please let me know what to add / improve to make it easier for you.
