### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by ghproek** [rust-or/good_lp#28]
This should be very easy to fix.  I believe the documentation here is in error (it says that two things are equivalent, but I don't see how they could be):

https://docs.rs/good_lp/1.4.0/good_lp/variable/struct.ProblemVariables.html#method.add

**Comment by lovasoa** [comment]
Oh yes, you are right, this is a mistake in the documentation. Can you make a small Pull Request to fix that?

**Comment by robbiemu** [comment]
submitted https://github.com/rust-or/good_lp/pull/34

**Comment by lovasoa** [comment]
What was the problem here? It looks like it was an example for the variables bounds syntax with two inequalities
