### ISSUE TITLE
HiGHS does depend on additional libs

### ISSUE THREAD

**Issue by CCHiggins** [rust-or/good_lp#29]
Readme mentions that HiGHS solver does not depend on additional libs at runtime, which is not wholly true.  The highs-sys crate mentions that the library depends on libstdc++ and libgomp at runtime. While most Linux distros include these libraries by default, mac needs to install libomp and lightweight container oriented Linux distros like alpine do not include the gcc tooling by default.

**Comment by lovasoa** [comment]
You are right ! It would be nice if we could statically link them in https://github.com/rust-or/highs-sys/blob/master/build.rs

**Comment by CCHiggins** [comment]
I think its possible but gcc is GPLv3 which as an infectious copyleft license, so anything statically linked against GPL libraries must also be released as GPL. It may be possible to static link against clang/LLVM versions which are apache?
