### ISSUE TITLE
Typos in repo description

### ISSUE THREAD

**Issue by KnorpelSenf** [rust-or/good_lp#46]
Current description of the repo:

```
Linear Programming for Rust, with an user-friendly API. This crate allows modeling LP problems, and let's you solve them with various solvers.
```

Fixed typos (an → a, let's → lets):

```
Linear Programming for Rust, with a user-friendly API. This crate allows modeling LP problems, and lets you solve them with various solvers.
```

Please update the description on GitHub :)

**Comment by lovasoa** [comment]
Thanks! Can you open a small pull request with the changes?

**Comment by KnorpelSenf** [comment]
Nope, you need to update the repository settings in the web interface (otherwise I would've opened a pull request directly)

**Comment by KnorpelSenf** [comment]
![-211270_temp](https://github.com/rust-or/good_lp/assets/12952387/39f064b6-25d2-4e84-ab01-fb5f05844cb5)
That thing there on the main repo page

**Comment by lovasoa** [comment]
Oh, sorry !

Fixed, thanks.
