### ISSUE TITLE
[Q/A] using HiGHs LP solver

### ISSUE THREAD

**Issue by DaveLanday** [rust-or/good_lp#50]
There is no discussion section for this repo to post a general Q/A, but I was wondering: can this crate allows me to use just the HiGHs LP solver? I want to write my own basic Branch and Bound implementation. Will highs.rs provide that level of control? 

Thanks!
Dave

**Comment by lovasoa** [comment]
Hello !
  Depending on the level of control you need, you may be happy with the [`HighsSolution`](https://docs.rs/good_lp/latest/good_lp/solvers/highs/struct.HighsSolution.html) that this crate provides, or need to use https://docs.rs/highs/latest/highs/ or even https://docs.rs/highs-sys

**Comment by DaveLanday** [comment]
Thank you for your reply! I will look there
