### ISSUE TITLE
Feature: add access to set_option for HiGHS

### ISSUE THREAD

**Issue by TeXitoi** [rust-or/good_lp#54]
Hi!

HighsProblem already gives access to a few solver options, but several are not available. Can’t we give full access to the `set_option` method?

If you are OK with this, I can open a PR on it.

Thanks!

**Comment by lovasoa** [comment]
Yes, I'd merge a pr for that. And maybe ass `as_inner_mut()` to give mutable access to the highs object ?

**Comment by TeXitoi** [comment]
OK, I’ll try to do this tomorrow.

**Comment by TeXitoi** [comment]
So, I looked at the code, and that’s not that simple…

we can’t have a `as_inner_mut` as the solver object is created and populate at `.solve()` time. Same for the options, as they are passed at that time. And the HiGHS crate use a strange trick to emulate method overload, so we can’t catch bad options easily.

I have a proposition just for the options.
