### ISSUE TITLE
MathOpt

### ISSUE THREAD

**Issue by KnorpelSenf** [rust-or/good_lp#59]
I would like to use MathOpt from Google's OR-Tools library. Would it be in scope for your crate to have support for it, or do you think it would be more reasonable to create a separate crate that contains the bindings?

https://developers.google.com/optimization/math_opt

**Comment by lovasoa** [comment]
Hi ! 

Based on the documentation you link, MathOpt does not seem to be a solver. It is an interface for accessing solvers. Which underlying solver did you plan on using ? Multiple are already supported by good_lp directly. If you need to a new solver, you can add support for that solver directly.

**Comment by KnorpelSenf** [comment]
Yes, I would like to be able to use that interface. But alright, I will build a separate crate.
