### ISSUE TITLE
Iteratively adding constraints to a large model

### ISSUE THREAD

**Issue by hangsuUNC** [rust-or/good_lp#61]
Hi,

I was trying to use good-lp to solve a mixed integer linear programing problem. Is it possible to iteratively adding constraints to a model? If yes, is there an example how to use the add_constraints() function?

Thanks,

Hang

**Comment by lovasoa** [comment]
The function you are looking for is probably https://docs.rs/good_lp/latest/good_lp/solvers/trait.SolverModel.html#method.with

there are many examples in this repo and in the documentation
