### ISSUE TITLE
Replace minilp with microlp

### ISSUE THREAD

**Issue by Specy** [rust-or/good_lp#64]
I've forked the minilp crate as it has been inactive for many years and wanted to do some bug fixes and update the dependencies, but especially have the repository open for PRs and improvements from others. I'm making this issue in case you want to replace minilp with [microlp](https://crates.io/crates/microlp)

**Comment by lovasoa** [comment]
Hi ! Yes, I'm open to it ! Could you add me to the maintainers of microlp (to prevent it from also becoming unmaintained in the future) ?
Then I'm open to merging a PR adding it to good_lp.

**Comment by Specy** [comment]
i've sent you an invite. 

Also, should the feature flag for microlp stay as minilp or change it to mincrolp?

**Comment by lovasoa** [comment]
can we have both ? To preserve backwards compatibility. We can always drop minilp later

**Comment by Specy** [comment]
do you mean feature flag or keeping both minilp and microlp as solvers?

**Comment by lovasoa** [comment]
I mean having both flags triggering microlp

**Comment by QTi1** [comment]
Question about microlp: why is it marked as not fast in the README? I've compared it head-to-head to clarabel (which is also in pure Rust) and highs (which parallelizes the computation) and microlp is consistently _faster_ than both others in release as well as debug mode, despite what the README says about debug mode. It could have something to do with the particular problem I'm trying to solve, I suppose.

**Comment by lovasoa** [comment]
microlp lacks many of the algorithms that other solvers have, for instance in presolving and integer programming. That's why it does not do well in benchmarks. If the problem is submitted in a form that cannot be simplified, I can see it be faster. 

There are many milp benchmarks, what we should do is run them with our solvers and indicate the results instead of just "fast/slow". Is someone motivated to do that?

**Comment by Specy** [comment]
> There are many milp benchmarks, what we should do is run them with our solvers and indicate the results instead of just "fast/slow".

We should definitely make this as a new issue
